<a href="https://colab.research.google.com/github/ZozolNat/python/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Урок 10. Построение графиков

Задача 44: В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего
из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без
get_dummies?

import random

lst = ['robot'] * 10

lst += ['human'] * 10

random.shuffle(lst)

data = pd.DataFrame({'whoAmI':lst})

data.head()

In [10]:
import pandas as pd
import random
import numpy as np
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  robot
1  human
2  robot
3  robot
4  robot

In [20]:
pd.get_dummies(data) # сделать так, но иначе

#data1 = pd.get_dummies(data['whoAmI'])
#data1.head()

    whoAmI_human  whoAmI_robot
0              0             1
1              1             0
2              0             1
3              0             1
4              0             1
5              1             0
6              1             0
7              0             1
8              1             0
9              0             1
10             1             0
11             0             1
12             1             0
13             1             0
14             0             1
15             0             1
16             1             0
17             0             1
18             1             0
19             1             0

In [36]:
data.loc[data['whoAmI'] == 'human', 'whoAmI_human'] = 1 # столбцы иначе смысл тот же
data.loc[data['whoAmI'] == "robot", 'whoAmI_robot'] = 1 

data.drop(data.columns[[0]], axis=1)

    whoAmI_robot  whoAmI_human
0            1.0           0.0
1            0.0           1.0
2            1.0           0.0
3            1.0           0.0
4            1.0           0.0
5            0.0           1.0
6            0.0           1.0
7            1.0           0.0
8            0.0           1.0
9            1.0           0.0
10           0.0           1.0
11           1.0           0.0
12           0.0           1.0
13           0.0           1.0
14           1.0           0.0
15           1.0           0.0
16           0.0           1.0
17           1.0           0.0
18           0.0           1.0
19           0.0           1.0